### ISSUE TITLE
Program Detail page does not list the Activities included in a Program.

### ISSUE THREAD

**Issue by sanjeetsuhag** [sanjeetsuhag/Westminster#27]
Once you click `Submit` after creating a program, you are redirected to a Program Detail page, which at the moment looks like this:

<img width="1439" alt="Program Detail Page" src="https://user-images.githubusercontent.com/5172619/28080091-b57a0052-6638-11e7-98fa-e2744dab125f.png">

The Activities in the Program are not listed. They should be displayed just like the tags are.

**Comment by SaulYin** [comment]
The issue is resolved, currently working on CSS and other stuff to make it look nice, but this bug is fixed. I will push my code after I finished the CSS and documenting work
